const crypto = require("crypto");
const createCrudRouter = require("./createCrudRouter");
const { User } = require("../Models");

function normalizeAccountType(value) {
  const normalized = String(value || "")
    .trim()
    .toLowerCase()
    .replace(/\s+/g, "_");

  const map = {
    regular: "regular",
    regular_user: "regular",
    internal: "internal",
    internal_user: "internal",
    admin: "admin",
    admin_user: "admin",
  };

  return map[normalized] || "regular";
}

function generateRandomPassword(length = 12) {
  const alphabet = "ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$";
  let out = "";
  for (let i = 0; i < length; i += 1) {
    out += alphabet[Math.floor(Math.random() * alphabet.length)];
  }
  return out;
}

function hashPassword(plainPassword) {
  const salt = crypto.randomBytes(16).toString("hex");
  const hash = crypto.scryptSync(plainPassword, salt, 64).toString("hex");
  return `scrypt$${salt}$${hash}`;
}

function verifyPassword(plainPassword, storedValue) {
  if (typeof storedValue !== "string" || !storedValue.startsWith("scrypt$")) {
    return false;
  }

  const parts = storedValue.split("$");
  if (parts.length !== 3) {
    return false;
  }

  const salt = parts[1];
  const hashHex = parts[2];
  if (!salt || !hashHex) {
    return false;
  }

  const expectedBuffer = Buffer.from(hashHex, "hex");
  const actualBuffer = crypto.scryptSync(plainPassword, salt, expectedBuffer.length);
  if (expectedBuffer.length !== actualBuffer.length) {
    return false;
  }

  return crypto.timingSafeEqual(expectedBuffer, actualBuffer);
}

function sanitizeUserDocument(userDoc) {
  const user = userDoc.toObject();
  delete user.passwordHash;
  return user;
}

const userRouter = createCrudRouter(User, {
  searchFields: ["fullName", "email", "phoneNumber", "accountType"],
  populate: ["client", "supplier"],
});

userRouter.post("/create-user", (req, res) => {
  const {
    fullName,
    email,
    phoneNumber,
    accountType,
    password,
    sendWelcomeEmail,
    client,
    supplier,
    settings,
  } = req.body;

  if (!email) {
    return res.status(400).json({ message: "email is required" });
  }

  const normalizedEmail = String(email).trim().toLowerCase();
  const manualPassword = typeof password === "string" ? password.trim() : "";
  const passwordAutoGenerated = manualPassword.length === 0;
  const generatedPassword = passwordAutoGenerated ? generateRandomPassword() : manualPassword;

  if (generatedPassword.length < 8) {
    return res.status(400).json({ message: "Password must be at least 8 characters" });
  }

  const shouldSendWelcomeEmail =
    typeof sendWelcomeEmail === "boolean" ? sendWelcomeEmail : passwordAutoGenerated;

  return User.findOne({ email: normalizedEmail })
    .lean()
    .then((existing) => {
      if (existing) {
        res.status(409).json({ message: "A user with this email already exists" });
        return null;
      }

      return User.create({
        fullName,
        phoneNumber,
        email: normalizedEmail,
        passwordHash: hashPassword(generatedPassword),
        accountType: normalizeAccountType(accountType),
        security: {
          passwordAutoGenerated,
          mustChangePassword: passwordAutoGenerated,
          passwordChangedAt: new Date(),
        },
        onboarding: {
          sendWelcomeEmail: shouldSendWelcomeEmail,
          welcomeEmailStatus: shouldSendWelcomeEmail ? "queued" : "not_requested",
          welcomeEmailSentAt: null,
        },
        client: client || null,
        supplier: supplier || null,
        settings: settings || {},
      });
    })
    .then((created) => {
      if (created) {
        res.status(201).json({
          message: "User created",
          user: sanitizeUserDocument(created),
          temporaryPassword: passwordAutoGenerated ? generatedPassword : undefined,
        });
      }
    })
    .catch((error) => res.status(400).json({ message: "Failed to create user", error: error.message }));
});

userRouter.post("/login", (req, res) => {
  const email = String(req.body?.email || "").trim().toLowerCase();
  const password = typeof req.body?.password === "string" ? req.body.password : "";

  if (!email) {
    return res.status(400).json({ message: "Email is required" });
  }

  if (!password) {
    return res.status(400).json({ message: "Password is required" });
  }

  return User.findOne({ email })
    .select("+passwordHash")
    .exec()
    .then((user) => {
      if (!user) {
        return res.status(401).json({ message: "Invalid email or password" });
      }

      if (!user.isActive) {
        return res.status(403).json({ message: "User account is inactive" });
      }

      const validPassword = verifyPassword(password, user.passwordHash);
      if (!validPassword) {
        return res.status(401).json({ message: "Invalid email or password" });
      }

      user.lastLoginAt = new Date();
      return user.save().then((savedUser) =>
        res.json({
          message: "Login successful",
          user: sanitizeUserDocument(savedUser),
          auth: {
            token: crypto.randomBytes(24).toString("hex"),
            issuedAt: new Date().toISOString(),
          },
        })
      );
    })
    .catch((error) => res.status(500).json({ message: "Failed to login", error: error.message }));
});

userRouter.patch("/:id/security/password", (req, res) => {
  const { password } = req.body;
  if (typeof password !== "string" || password.trim().length < 8) {
    return res.status(400).json({ message: "password must be at least 8 characters" });
  }

  return User.findByIdAndUpdate(
    req.params.id,
    {
      $set: {
        passwordHash: hashPassword(password.trim()),
        "security.passwordAutoGenerated": false,
        "security.mustChangePassword": false,
        "security.passwordChangedAt": new Date(),
      },
    },
    { new: true, runValidators: true }
  )
    .exec()
    .then((user) => {
      if (!user) {
        return res.status(404).json({ message: "User not found" });
      }
      return res.json({ message: "Password updated", user: sanitizeUserDocument(user) });
    })
    .catch((error) => res.status(400).json({ message: "Failed to update password", error: error.message }));
});

userRouter.patch("/:id/onboarding/welcome-email", (req, res) => {
  const { sendWelcomeEmail, welcomeEmailStatus } = req.body;
  const update = {};

  if (typeof sendWelcomeEmail === "boolean") {
    update["onboarding.sendWelcomeEmail"] = sendWelcomeEmail;
  }

  if (typeof welcomeEmailStatus === "string") {
    update["onboarding.welcomeEmailStatus"] = welcomeEmailStatus;
    if (welcomeEmailStatus === "sent") {
      update["onboarding.welcomeEmailSentAt"] = new Date();
    }
  }

  return User.findByIdAndUpdate(req.params.id, { $set: update }, { new: true, runValidators: true })
    .exec()
    .then((user) => {
      if (!user) {
        return res.status(404).json({ message: "User not found" });
      }
      return res.json({ message: "Onboarding settings updated", user: sanitizeUserDocument(user) });
    })
    .catch((error) =>
      res.status(400).json({ message: "Failed to update onboarding settings", error: error.message })
    );
});

module.exports = userRouter;
