const mongoose = require("mongoose");

const userSchema = new mongoose.Schema(
  {
    fullName: {
      type: String,
      trim: true,
    },
    email: {
      type: String,
      required: true,
      unique: true,
      lowercase: true,
      trim: true,
    },
    phoneNumber: {
      type: String,
      trim: true,
      default: "",
    },
    passwordHash: {
      type: String,
      required: true,
      select: false,
    },
    accountType: {
      type: String,
      enum: ["regular", "internal", "admin"],
      default: "regular",
      required: true,
    },
    security: {
      passwordAutoGenerated: {
        type: Boolean,
        default: false,
      },
      mustChangePassword: {
        type: Boolean,
        default: false,
      },
      passwordChangedAt: {
        type: Date,
        default: null,
      },
    },
    onboarding: {
      sendWelcomeEmail: {
        type: Boolean,
        default: false,
      },
      welcomeEmailStatus: {
        type: String,
        enum: ["not_requested", "queued", "sent", "failed"],
        default: "not_requested",
      },
      welcomeEmailSentAt: {
        type: Date,
        default: null,
      },
    },
    client: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Client",
      default: null,
    },
    supplier: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Supplier",
      default: null,
    },
    isActive: {
      type: Boolean,
      default: true,
    },
    settings: {
      type: mongoose.Schema.Types.Mixed,
      default: {},
    },
    lastLoginAt: {
      type: Date,
      default: null,
    },
  },
  { timestamps: true }
);

module.exports = mongoose.model("User", userSchema);
